### ISSUE TITLE
Preparing arguments for evaluation

### ISSUE THREAD

**Issue by swathimudda** [jpmml/jpmml-evaluator#124]
Hi,

I have a list of input fields for which I am preparing the arguments for evaluation in loop. The fields are all of type ContinuousDouble. I have tried both the eager and manual preparation of arguments. However, I keep getting "Method threw 'java.lang.NoSuchMethodError' exception. Cannot evaluate org.jpmml.evaluator.ContinuousValue$ContinuousDouble.toString()". On debugging, I see that the error is thrown when a new instance of ContinuousDouble is returned on the create method of the ContinuousValue class. I don't see any usage of toString() anywhere, though. Can you help me find out what the actual issue might be?

Thanks.

**Comment by vruusmann** [comment]
>  I keep getting "Method threw 'java.lang.NoSuchMethodError' exception.

The solution to your problem is contained in the stack trace of this NSME. By making a wild guess, I would think that class `ContinuousValue.DoubleValue` cannot be loaded, because the classpath for the underlying `FieldValue#toString()` method is incomplete - specifically, class `org.jpmml.model.ToStringHelper` is not available on classpath.

> Can you help me find out what the actual issue might be?

Mismatching JPMML-Model and JPMML-Evaluator library versions.

In your project, you ONLY need to declare the JPMML-Evaluator  dependency - it will automatically fetch all other dependencies, including the correct version of the JPMML-Model dependency.
