### ISSUE TITLE
speeding up lightGBM evaluation

### ISSUE THREAD

**Issue by bakhtiary** [jpmml/jpmml-evaluator#149]
Hi,

We are experimenting with speeding up a lightGBM pipeline. It consists of a DFMapper followed by a lightGBM regressor. When we use the evaluator example with the --optimize option we need 0.1 milliseconds per evaluation. On the python side the pipeline takes 0.001 milliseconds per evaluation.

I wanted to know of the ways that exist to speed up the pipeline. I can switch to xgboost or scikitlearn GBR but as far as I can tell they get encoded in the same manner and would result in the same performance. 

Do you think it would be possible to optimize the model such that the lightGBM step would be handle by a native implementation? 

Or maybe you could suggest some other optimization approach.

Best,
Amir

**Comment by vruusmann** [comment]
> I can switch to xgboost or scikitlearn GBR but as far as I can tell they get encoded in the same manner...

That's the whole point of a standardized intermediate representation (such as PMML) - many different input data formats converge to one standardized data format, and they you have a chance to build an optimized executor for this one data format.

> ... and would result in the same performance.

Depends on the "feature composition" of your dataset/model - how many features in total, how many continuous/categorical, what's the cardinality of categoricals, etc.

(J)PMML gets _relatively_ better when the complexity of the dataset/model increases.

> Do you think it would be possible to optimize the model such that the lightGBM step would be handle by a native implementation?

The Java/JVM implementation is expected to be slower than native C/C++ implementation. That should be the case with every application scenario.

> Or maybe you could suggest some other optimization approach.

I'm working on an improved scoring engine, which attempts to detect and transpile (translate + compile) expensive parts. But this is a private/proprietary codebase, which will not be available publicly.

**Comment by bakhtiary** [comment]
Thank you for your comments. They are very insightful and will help me make a decision.

**Comment by vruusmann** [comment]
@bakhtiary What was your approximate benchmarking configuration? I'm asking, because a 100x difference between JPMML-Evaluator and native LightGBM is a bot too much; I would expect it to be in 10x-20x range at worst.

For example, your JPMML timings probably include time, which was spent on loading PMML from the file and then pre-processing it (eg. travensing the PMML class model object, and parsing Strings to built-in datatypes). Nothing like this is included in native LightGBM scenario, because the LightGBM model was already sitting nicely in memory etc.

The `org.jpmml.evaluator.EvaluationExample` command-line applications provides a large number of hidden command-line options. For example, to allow the JVM to properly warm up, you should iterate over the sample dataset many times using the `--loop` command-line option.
