### ISSUE TITLE
Extended support for the `clusterAffinity` output feature

### ISSUE THREAD

**Issue by sfr** [jpmml/jpmml-evaluator#15]
Hi,

following code (using 1.2.5 release):
```java
final Map<FieldName, ?> results = kMeansModel.evaluate(params);
for (final Entry<FieldName, ?> resultEntry : results.entrySet())
{
	System.out.printf("%s = %s%n", resultEntry.getKey(), resultEntry.getValue());
}
```

returns this:
```
null = ClusterAffinityDistribution{result=5, distance_entries=[1=46.498128117308376, 2=47.12002804402491, 3=49.17335819210169, 4=43.117652229258695, 5=39.95722874558617, 6=45.533022467040844, 7=46.711182656888525], entityId=5}
predictedValue = 5
clusterAffinity_1 = 39.95722874558617
clusterAffinity_2 = 39.95722874558617
clusterAffinity_3 = 39.95722874558617
clusterAffinity_4 = 39.95722874558617
clusterAffinity_5 = 39.95722874558617
clusterAffinity_6 = 39.95722874558617
clusterAffinity_7 = 39.95722874558617
```

shouldn't the clusterAffinity_? have the same values as in the first line?

Regards,
    Juraj.

**Comment by vruusmann** [comment]
Your `Output` element contains seven `OutputField` elements, which are expected to yield the distance of the data record to seven clusters `1` to `7`. Contrary to expectations, all `OutputField` elements yield the distance to the one and the same cluster, which is the winning cluster `5`.

This behaviour boils down to the `OutputField@feature` attribute. According to the [PMML specification] (http://dmg.org/pmml/v4-2-1/Output.html) the value of this attribute can be specified as `clusterAffinity`, `entityAffinity` or simply `affinity`. In JPMML-Evaluator interpretation of the PMML specification, the former two return the distance to the winning entity, and only the latter one returns the distance to the specified entity (please see the Java source code of class `org.jpmml.evaluator.OutputUtil`, lines 245 to 255).

So, I suspect your clustering model specifies the value of `OutputField@feature` attribute as `clusterAffinity`, but it should be `affinity` instead. Is your clustering model generated by R's "pmml" package perhaps? Also, could you paste its `Output` element here so that we could analyze it together?

**Comment by sfr** [comment]
Thanks for clarification.

You are correct in both cases. Output specifies clusterAffinity and it was generated by R's pmml package.

```xml
<Output>
	<OutputField name="predictedValue" feature="predictedValue"/>
	<OutputField name="clusterAffinity_1" feature="clusterAffinity" value="1"/>
	<OutputField name="clusterAffinity_2" feature="clusterAffinity" value="2"/>
	<OutputField name="clusterAffinity_3" feature="clusterAffinity" value="3"/>
	<OutputField name="clusterAffinity_4" feature="clusterAffinity" value="4"/>
	<OutputField name="clusterAffinity_5" feature="clusterAffinity" value="5"/>
	<OutputField name="clusterAffinity_6" feature="clusterAffinity" value="6"/>
	<OutputField name="clusterAffinity_7" feature="clusterAffinity" value="7"/>
</Output>
```

Thanks again,
	Juraj

**Comment by vruusmann** [comment]
If you read the description of `clusterAffinity` and `affinity` feature values in the PMML specification, then do you agree with JPMML-Evaluator's interpretation or not? Maybe JPMML-Evaluator is simply too strict here.

Obviously, it would be straightforward to add a "helper" routine which detect the presence of a non-null `OutputField@value` attribute, and then treats the `clusterAffinity` feature value synonymously to the `affinity` feature value. This might be worth doing, given that there are probably plenty of clustering model PMML documents that are broken in this specific way, and that it's impossible to get anything fixed with the R's "pmml" package.

**Comment by vruusmann** [comment]
For documentation purposes, JPMML-Evaluator evaluates the `clusterAffinity` feature according to the following excerpt of the PMML specification (schema version 4.2.1):
```
clusterAffinity is the value of the distance or the similarity .. to the cluster center given in clusterId.
```
In this example, the value of the `clusterId` is `5`. Therefore, all seven `OutputField` elements yield the distance to the fifth cluster, which is `39.95722874558617`.

**Comment by sfr** [comment]
*"This specification supports only the distance to the cluster center given in ```clusterId```, NOT the distance to the nearest center."*

I do not think that the definition means ```clusterId``` that is calculated. I think that it is the ```clusterId``` that suppose to be in the ```value``` attribute. Cause if it was the calculated ```clusterId```, then the value would be the same as the distance to the nearest center. And specifications clearly says that it is not the case.

**Comment by sfr** [comment]
I would suggest, and probably it doesn't go against the specification; if the ```value``` is specified, then it is the similarity/distance to that cluster. And when there is no ```value``` then it is the similarity/distance to the nearest cluster.

Output, where with a specified concrete cluster Id and some other value is very misleading.
```
clusterAffinity_1 = 39.95722874558617
clusterAffinity_2 = 39.95722874558617
clusterAffinity_3 = 39.95722874558617
...
```

Last week when I saw output like this, I thought that there is something wrong with my model and I went through the whole research with a magnifying glass to find an error. And it was a huge relief today when I found this.

**Comment by vruusmann** [comment]
I agree with your interpretation that it should be possible to override the default cluster with the user-specified cluster using the `OutputField@value` attribute. Otherwise it would be impossible to extract detailed affinity information from clustering models.

The fix is part of the JPMML-Evaluator library version 1.2.6, which should be available via the Maven Central repository starting tomorrow.

**Comment by sfr** [comment]
Awesome. Thanks for a great product.
