### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by prachikhadke** [jpmml/jpmml-evaluator#181]
Hi

I am wondering why you use the AGPL license for this library. All code vulnerability scanners mark this library as having a vulnerability due to the AGPL license. However, this is the only comprehensive library for jpmml. So I wondered why you would use an AGPL license and if you would be open to using another license.

Regards
Prachi

**Comment by vruusmann** [comment]
> I am wondering why you use the AGPL license for this library.

Because I need to provide for myself and my family?

> However, this is the only comprehensive library for jpmml.

The JPMML software project in its current form (https://github.com/jpmml) wouldn't exist if it wasn't licensed under AGPLv3 by default. During its 5+ years in existence, it hasn't received a single donation/grant/other act of sponsorship.

> I wondered if you would be open to using another license.

The "License" section of the README file states that everything is actually dual licensed - the AGPLv3 is the default option, but there's also a commercial license available. You'd need to drop me an e-mail to learn about the latter - it's not a software bug/issue.
