### ISSUE TITLE
Support for DeepNetwork

### ISSUE THREAD

**Issue by AbdealiJK** [jpmml/jpmml-evaluator#204]
Hi, this is more of a question on the future plan of support of DeepNetwork .

I am wondering if there is some plan of JPMML supporting DeepNetwork which as I understand it is not a part of the official PMML-4.4 but seems to be getting used in some libraries ?

I was creating some PMMLs using:
 - nyoka: https://github.com/SoftwareAG/nyoka
 - python-pmml: https://github.com/maxkferg/python-pmml/tree/master/models/deepnetwork

And got some errors, found others mentioning the same issue:
 - https://github.com/SoftwareAG/nyoka/issues/23

I am wondering if it there is any plan to support an experimental DeepNetwork in jpmml-evaluator too ?
Or will that only be done if a new spec for PMML is created with DeepNetwork ?

Other links:
 - https://pdfs.semanticscholar.org/f626/0978f30443388f4df5f7ab7c267a06edb750.pdf

**Comment by vruusmann** [comment]
Thanks for taking the time to collect and provide so much information, especially the last PDF reference (who has time for browsing scholarly articles?)!

> I am wondering if it there is any plan to support an experimental DeepNetwork in jpmml-evaluator too ?

The `DeepNetwork` is a proprietary model element, and I don't think it's possible for a third party to build a complete and reliable implementation of it. If you need `DeepNetwork`, then you should probably switch away from JPMML-Evaluator to whatever this other vendor is trying to sell.

> Or will that only be done if a new spec for PMML is created with DeepNetwork ?

The `DeepNetwork` element seems like reinventing the wheel.

If one needs to represent and persist DNN models, then one should consider using the ONNX standard for that. I've got the impression that ONNX is actively developed and well funded.

What PMML (schema version 5.0?) needs is a way to interoperate with other standards such as ONNX, not try to re-create them. Instead of the `DeepNetwork` element, there could/should be an `ONNXModel` element.

**Comment by AbdealiJK** [comment]
@vruusmann Thanks, understood
Appreciate your inputs. I was looking at ONNX today and I had the same impression that it has vecome wuite stable since last I saw it. With decent converters for popular libraries.

Will take a look at that
