### ISSUE TITLE
Bring JAXB dependencies from "provided" scope to "compile" scope

### ISSUE THREAD

**Issue by schefflaa** [jpmml/jpmml-evaluator#213]
Hey there. I am currently trying to implement a minimal working example that reads a `.csv` file as input for the model and a `.pmml` file to build the model from. I am referring to the "Basic Usage" section of your `readme.md`.

The `LoadingModelEvaluatorBuilder()` function `load()` is declared to throw a `javax.xml.bind.JAXBException`. From [what I've read in other threads](https://stackoverflow.com/questions/43574426/java-how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexceptio) this exception is removed from JDK 11 and a solution would be to use the _JAX-B API_ as a maven dependency instead (see post).

However, this exception does not match the thrown exception and therefore the `class file (..) not found` exception is thrown when trying to build the application.

Does this mean the jpmml-evaluator is not supported for JDK11 or am I missing the correct solution?

**Comment by vruusmann** [comment]
> From what I've read in other threads this exception is removed from JDK 11

JAXB clases were not removed (in a sense that the contents of the `javax.xml.bind` has been cancelled), they were simply moved into a standalone JAXB module (starting from Java 9).

If you want to build and run a JAXB-enabled Java application, then you have two options:
1) Use Java's built-in module mechanism to "import and activate" the JAXB module. There's some command-line switch for that.
2) Add a JAXB dependency directly to your applications' classpath.

I personally find option #2 better, because I can choose between different JAXB implementations (Glassfish Metro, EclipseLink MOXy) and versions.

For example, you can include Glassfish Metro JAXB runtime using the following dependency declaration:
```xml
<dependency>
	<groupId>org.jpmml</groupId>
	<artifactId>pmml-model-metro</artifactId>
	<version>${jpmml-model.version}</version>
</dependency>
```

You should check out the [JPMML-Model](https://github.com/jpmml/jpmml-model) library for more details.

> Does this mean the jpmml-evaluator is not supported for JDK11 or am I missing the correct solution?

JPMML-Evaluator supports Java 1.8 and all newer Java SE versions.

The project is covered with GitHub Actions CI, which runs unit tests on all Java 8, 9, 10, 11, 12, 13, and 14:
https://github.com/jpmml/jpmml-evaluator/actions?query=workflow%3Amaven

There is not a single `ClassNotFoundException` being reported.

**Comment by schefflaa** [comment]
Thanks a lot! Got it to run after adding the maven dependency and fixing the imports. Was just confused as this dependency configuration is not explicitly listed anywhere.

**Comment by vruusmann** [comment]
> Was just confused as this dependency configuration does not seem to be explicitly listed anywhere.

Fair observation.

Right now, the main module `org.jpmml:pmml-evaluator` lists both JAXB runtime libraries, but assigns them to the "provided" scope (which means that the application user should explicitly re-declare them):
https://github.com/jpmml/jpmml-evaluator/blob/1.5.11/pmml-evaluator/pom.xml#L32-L41

Perhaps it's time to change their scope from "provided" to "compile" (aka default).

The document could be updated right now, but the scope change should probably wait until the next major release (ie. the 1.6.X development branch).
