### ISSUE TITLE
WARNUNG: CSV evaluation failed: Mark invalid

### ISSUE THREAD

**Issue by philipus** [jpmml/jpmml-evaluator#24]
hi

i got a very simple message 

Apr 20, 2016 5:21:58 PM org.openscoring.client.CsvEvaluator run
WARNUNG: CSV evaluation failed: Mark invalid

form the evaluation:

"java -cp $jpmml/target/client-executable-1.2-SNAPSHOT.jar org.openscoring.client.CsvEvaluator --model http://localhost:8080/openscoring/model/460012_p_aktiv --input ~/test.csv --output ~/test_output.csv

any Idea???

has it to do with my missing (jpmml- xgboost)

# Generate DMatrix file
mpg.dmatrix = genDMatrix(mpg_y, mpg_X, "xgboost.svm")

part?? I realised that i dont need xgboost.svm in order to get the pmml file

i simple used 

xgboost(param=param, 
                            data = data.matrix(training[,feature.names]), 
                            label=training$aktiv_target, 
                            nrounds=trounds_tmp,
                            base_score = base,
                            missing=NA
  )

so I used the implicit transform of the data from xgboost

**Comment by vruusmann** [comment]
The exception message "Mark invalid" is related to the Super-CSV library, which deals with parsing the input CSV file: https://sourceforge.net/p/opencsv/bugs/115/

In other words, looks like the line length of your CSV file is greater than the default buffer size (IIRC, you were working with 3000 feature columns?). I will open a new issue about it.

If you're interested in testing the evaluation of XGBoost PMML models, then you could use the `org.jpmml.evaluator.EvaluationExample` command-line application (instead of messing with the full Openscoring server/client setup). The instructions for doing so are given in the "Example applications" section of the README.md file: https://github.com/jpmml/jpmml-evaluator/blob/master/README.md

Something like this:
```
java -cp target/example-1.2-SNAPSHOT.jar org.jpmml.evaluator.EvaluationExample --model xgboost.pmml --input test.csv --output test_output.csv
```

**Comment by vruusmann** [comment]
Closing this issue in favour of the following one:
https://github.com/jpmml/openscoring/issues/11
