### ISSUE TITLE
different results in evaluation

### ISSUE THREAD

**Issue by philipus** [jpmml/jpmml-evaluator#25]
I get different results in evaluation from using predict in R in comparison in using published pmml code via jpmml-xgboost and openscoring

interested in sample data set? and the r code?!

**Comment by vruusmann** [comment]
Sure, I would be interested in looking at the model and the actual data, and tracking down the problem.

You could prepare the following files:
1. Save the `xgb.Booster` object using the `xgboost::xgb.save()` function as a binary file.
2. Save the associated feature map as a text file.
3. Select approximately 10 "problematic" data records. Predict them using the `xgboost::predict.xgb.Booster()` function so that I will know what are the expected correct results.

You could send the above files to my e-mail if you don't want to share them publicly with the world.

If you're interested in debugging the problem locally, then you could try dumping the `xgb.Booster` object using the `xgboost::xgb.dump()` function. If you compare the contents of this text dump file with the PMML file, can you spot any obvious structural differences? I'm afraid that there may be a problem with your feature map - for example, some double fields could be tagged as integer fields (or vice versa).

**Comment by vruusmann** [comment]
Closing this issue, because the user has not provided any actionable feedback/data.

Most likely, the PMML representation of the XGBoost model is incorrect, because the user has used an invalid/out-of-sync description of the feature map when performing the XGBoost-to-PMML conversion.

**Comment by fatihtekin** [comment]
I am having a similar issue as well.

https://github.com/jpmml/jpmml-sparkml-xgboost/issues/1
