### ISSUE TITLE
ServiceLoadingModelEvaluatorBuilder.loadService

### ISSUE THREAD

**Issue by OOYXLOO** [jpmml/jpmml-evaluator#257]
How can I get an Evaluator from xxx.pmml.jar through the ServiceLoadingModelEvaluatorBuilder in a packaged jar?

I can't use this.getClass().getClassLoader().getResource("xxx.pmml.jar") to get the URL which is needed in SerciceLoadingModelEvaluatorBuilder.loadService to get an Evaluator because in a packaged jar I can't get the path.

I know that I can use LoadingModelEvaluatorBuilder to get an Evaluator from a xxx.pmml, but the unmarshal step will cost much time when I need to load abundant models.

I hope that someone can help me to solve this problem

**Comment by vruusmann** [comment]
> How can I get an Evaluator from xxx.pmml.jar through the ServiceLoadingModelEvaluatorBuilder in a packaged jar?

The Java API can be derived from the class name: "serviceLoading" + "builder":

```java
URL serviceJarURL = ...;

// First do "loadService", then do "build"
Evaluator evaluator = new ServiceLoadingModelEvaluatorBuilder()
	.loadService(serviceJarURL)
	.build();
```

> I can't use this.getClass().getClassLoader().getResource("xxx.pmml.jar")

The `ClassLoader#getResource(String)` method is looking for a resource **_inside_** classpath JAR files.

Your `xxx.pmml.jar` service JAR file is **not** located inside any other JAR files, it is a standalone top-level JAR file all by itself (that's how it's supposed to work, if you have generated a "wrapped JAR file" already, then please unwrap it).

More importantly, the `xxx.pmml.jar` service JAR file does not need to be on your Java application's classpath. The Java classloader only knows about classpath contents so, by design, this `xxx.pmml.jar` service JAR file can/should be unknown to Java classloader initially.

> I know that I can use LoadingModelEvaluatorBuilder to get an Evaluator from a xxx.pmm

The right question to ask is "how can I obtain a `java.net.URL` object pointing to my xxx.pmml.jar?"

Assuming a file in local filesystem:
```java
File serviceJarFile = new File("/path/to/xxx.pmml.jar");

URL serviceJarURL = (serviceJarFile.toURI()).toURL();
```

Assuming a resource on some publicly accessible web seriver:
```java
URL serviceJarURL = new URL("https://myserver.com/mydir/xxx.pmml.jar");
```

> .. but the unmarshal step will cost much time when I need to load abundant models.

Yep, that's one valid reason for choosing JPMML-Transpiler over the standard JPMML-Evaluator - transpiled models do not have any Ja(va|karta) XML Binding dependencies, and they load blazing fast.

**Comment by OOYXLOO** [comment]
Thank you very much, I will solve the problem according to your suggestion.
