### ISSUE TITLE
inputFiled.prepare  error

### ISSUE THREAD

**Issue by Alexkevin** [jpmml/jpmml-evaluator#32]
When I run the following code 
```
Object rawValue = 1.0;
FieldValue activeValue = input.prepare(rawValue);
```

The error always happen:
```
Exception in thread "main" org.jpmml.evaluator.InvalidResultException
	at org.jpmml.evaluator.FieldValueUtil.performInvalidValueTreatment(FieldValueUtil.java:190)
	at org.jpmml.evaluator.FieldValueUtil.prepareInputValue(FieldValueUtil.java:94)
	at org.jpmml.evaluator.InputField.prepare(InputField.java:64)
	at cn.pmml.test1.PMMLTest.arguments(PMMLTest.java:87)
	at cn.pmml.test1.PMMLTest.main(PMMLTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

I tried many ways to fix that, but all failed.

**Comment by Alexkevin** [comment]
I tried in this way 
`            FieldValue activeValue = FieldValueUtil.create(1.0);
            arguments.put(activeName,activeValue);`


It works

**Comment by vruusmann** [comment]
What is the `DataField` element that is backing the `input` variable? The `InvalidResultException` shows that it's either 1) not a numeric field, or 2) is a numeric field, but the value `1.0` is outside of its valid value space.

You're probably making the mistake that you're trying to use the same `input` variable to prepare all active field values. You need to invoke `InputField#prepare(Object)` for each active field separately (see the code example in README.md):
```
List<InputField> activeFields = evaluator.getActiveFields();
for(InputField activeField : activeFields){
  Object userValue = userArguments.get(activeField.getName());
  FieldValue preparedActiveValue = activeField.prepare(userValue); // THIS! You invoke InputField#prepare(Object) only once for each InputField instance
  arguments.put(activeField.getName(), preparedActiveValue());
}
```

**Comment by vruusmann** [comment]
Please note that the JPMML-Evaluator library has been updated to new major version, which means that you need to **unlearn** some `1.2.X` API pieces, and **learn** some `1.3.X` API pieces.

Preparing fields using 1.2.X API:
```
List<FieldName> activeFields = evaluator.getActiveFields(); // The List element type is org.dmg.pmml.FieldName
for(FieldName activeField : activeFields){
  evaluator.prepare(activeField, userArguments.get(activeField)); // The preparation is handled by Evaluator#prepare(FieldName, Object). The active field is identified by name.
}
```

Preparing fields using 1.3.X API:
```
List<InputField> activeFields = evaluator.getActiveFields(); // The List element type is org.jpmml.evaluator.InputField
for(InputField activeField : activeFields){
  activeField.prepare(userArguments.get(activeFields.getName())); // The preparation is handled by InputField#prepare(Object). The InputField instance contains all the information about the active field, so there's no need to provide any additional data
}
```

From the end user perspective, the new API is much more compact and elegant (eg. the number of methods in `Evaluator` interface just got cut in half).

From the JPMML-Evaluator developer perspective, it avoids many repeated field lookups by name (ie. no need to do `#getDataField(FieldName)` and `#getMiningField(FieldName)`, because all this information is readily provided by the `InputField` instance), which is expected to deliver significant performance improvements in near future.
