### ISSUE TITLE
why PMMLEvaluationContext is invisible？

### ISSUE THREAD

**Issue by candyzone** [jpmml/jpmml-evaluator#33]
Hello,
In this commit (https://github.com/jpmml/jpmml-evaluator/commit/a309d50ab8fc0a051d69f6e07070f45f1d3087f5) "Restricted the visibility of EvaluationContext constructors", you remove the access control "public", so that I cannot new java object "PMMLEvaluationContext"
1. Why do that?
2. In my code, I use PMMLEvaluationContext to process DataTransformation with a non-model PMML file. In the lastest version, how can I do DataTransformation(PMML file only contain <DataTransformation>) in another way?

**Comment by vruusmann** [comment]
> Why do that?

Class `EvaluationContext` (and its subclasses) are not part of the public API. In fact, I can't imagine a valid/supproted workflow, where it would be necessary to work with it directly.

> In the lastest version, how can I do DataTransformation(PMML file only contain ) in another way?

Class `PMMLEvaluationContext` has been removed in the 1.3.X development branch altogether. The reason is that the PMML specificiation does not define rules for performing evaluations "outside" of a Model element. The case in point is the requirement that "all fields values must flow through the MiningSchema element" - it's necessary to apply all sorts of missing/invalid/outlier treatments to a field value before it becomes usable.

You could emulate `PMMLEvaluationContext` by inserting a dummy Model element into your PMML document, and using the associated `ModelEvaluationContext` instead.

Also, please note that you can always use Java reflection to bypass such constraints. If you know that there is a private constructor that you absolutely must use, then look it up using `Class#getDeclaredConstructor(Class...)`, and make it accessible by calling `Constructor#setAccessible(true)` on it.

Thanks for pointing out this "leaky" abstraction - I'll go and tighten screws in this area even more in the subsequent 1.3.X versions :-)
