### ISSUE TITLE
Attempt to invoke virtual method 'boolean org.dmg.pmml.PMML.hasModels()' on a null object reference

### ISSUE THREAD

**Issue by leslietso** [jpmml/jpmml-evaluator#37]
I am currently attempting to evaluate the a .pmml model created with sklearn2pmml. However, whenever I attempt to run the code `ModelEvaluator<NearestNeighborModel> modelEvaluator = new NearestNeighborModelEvaluator(pmml);`, I get the following error:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.dmg.pmml.PMML.hasModels()' on a null object reference
  at org.jpmml.evaluator.ModelEvaluator.selectModel(ModelEvaluator.java:584)
  at org.jpmml.evaluator.nearest_neighbor.NearestNeighborModelEvaluator.<init>(NearestNeighborModelEvaluator.java:105)
  at com.mygdx.game.DrawView.pitchAngle(DrawView.java:295)
  at com.mygdx.game.StartGdxGame.render(StartGdxGame.java:113)
  at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:459)
  at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
  at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
```

I have double checked and the code can find and has access to the .pmml-file and a model does exist in the .pmml file in the form `<NearestNeighborModel functionName="regression" numberOfNeighbors="400" continuousScoringMethod="average">`. 

Is there any other reason for the error? Did I maybe compile the .pmml incorrectly?

**Comment by vruusmann** [comment]
Looks like you have passed `null` argument to the `NearestNeighborModelEvaluator(PMML)` constructor. Have you double-checked it already?

JPMML-Evaluator works fine on Android. However, it may be a bit tricky to obtain the `org.dmg.pmml.PMML` class model object, because you cannot parse PMML documents using the JAXB framework. The only option is to de-serialize it from a Java serialization document.

Have you seen the [JPMML-Android](https://github.com/jpmml/jpmml-android) project?

**Comment by leslietso** [comment]
Sorry for the late reply but I've been testing out JPMML-Android. I've been looking over the code of JPMML-Android and I can not seem to find the part where you serialize the pmml file. How did you create the `model.pmml.ser` file without using `JAXBUtil.unmarshalPMML()` to generate the `org.dmg.pmml.PMML`?

**Comment by vruusmann** [comment]
The `model.pmml.ser` file is generated using `org.jpmml:pmml-maven-plugin` Maven plugin, which is part of the [JPMML-Model](https://github.com/jpmml/jpmml-model) project. It happens during the packaging of the Android application APK.

Here's an example:
https://github.com/jpmml/jpmml-android/blob/master/pmml-android-example/pom.xml#L52

**Comment by chenguangshen** [comment]
@vruusmann Thanks for the pointer. Any idea on whether it is possible to invoke this plugin in Android Studio/gradle instead of Maven? I understand that you can put a repo url in the top-level gradle file and import the library in the module-level gradle file to import a maven library, but I am not sure if the actual transformation defined by `execution` can be performed using gradle.

Alternatively, do you have a pointer to a piece of code for transforming a model in PMML to SER?

**Comment by vruusmann** [comment]
@chenguangshen The `SER` file is just a Java Serialization file:
```
org.dmg.pmml.PMML pmml = ...;
try(OutputStream os = new FileOutputStream("model.ser")){
  ObjectOutputStream oos = new ObjectOutputStream(os);
  oos.writeObject(pmml);
  oos.close();
}
```

For more details, see the `SerMojo` class that is part of the `pmml-maven-module` of the JPMML-Model project:
https://github.com/jpmml/jpmml-model/blob/master/pmml-maven-plugin/src/main/java/org/jpmml/model/plugin/SerMojo.java#L192

**Comment by chenguangshen** [comment]
@vruusmann Thanks, this is very helpful!
