### ISSUE TITLE
Performance issues while running evaluator for multiple threads #1

### ISSUE THREAD

**Issue by GRaote** [jpmml/jpmml-evaluator#38]
My .pmml file contains ~900 input fields of type double.
I'm running an application which runs on a multi-threaded environment evaluating with 30 threads.
Since there's a method in org.jpmml.evaluator.TypeUtil Line 208 - return (Double.parseDouble(value) + 0d); it has one synchronized method which blocks 29 threads and affects the overall performance
Ref: http://dalelane.co.uk/blog/?p=2936
I did a workaround adding this class from
https://gist.github.com/dalelane/7720269
and calling 
return (DoubleParser.parseDouble(value) + 0d);
on line 208 which solved the issued.

Suggest you to do the same if required.

**Comment by mackaiver** [comment]
Hi @GRaote ,
I'm having similar problems. However If I understand this JDK issue correctly this should have been fixed in java 8/9. And I'm currently on 8.
https://bugs.openjdk.java.net/browse/JDK-7032154

Do you know something about that?

**Comment by mackaiver** [comment]
Ok I think this might help. 
http://stackoverflow.com/questions/10577610/what-is-difference-between-double-parsedoublestring-and-double-valueofstring

@vruusmann maybe simply replace the call with `Double.valueOf` and `Float.valueOf` ?

right now these methods take away 30-40% of our processing time.

**Comment by mackaiver** [comment]
Also come to think of it. I'm not quite sure whats going on at all. 
I'm evaluating a large tree model on a stream of data. The profile clearly tells me that the `parseFloat()` method within the evaluation of the trees predicate is the bottleneck. Does this mean the split values in each node are parsed from some string token each time? That seems kind of excessive since these values never change once the pmml file has been parsed right?

**Comment by vruusmann** [comment]
@mackaiver @alexeyegorov

> Does this mean the split values in each node are parsed from some string token each time?

Yes, this the default behaviour.

In your tree model you have node predicates like this:
```XML
<Node>
  <SimplePredicate field="x" operator="lessThan" value="0.5"/>
</Node>
```

Method `org.dmg.pmml.SimplePredicate#getValue()` returns you a `java.lang.String` value, which needs to be parsed to a `java.lang.Number` subclass value before it becomes possible to evaluate the "lessThan" operator.

In the worst case, the same String value could be parsed two times during the evaluation of some Node level (first for the "if" clause, which doesn't fire, and then for the "else if" clause, which fires):
```XML
<Node>
  <!-- If x < 0.5 -->
  <Node>
    <SimplePredicate field="x" operator="lessThan" value="0.5"/>
  </Node>
  <!-- else if x >= 0.5 -->
  <Node>
    <SimplePredicate field="x" operator="greaterOrEqual" value="0.5"/>
  </Node>
</Node>
```

As a temporary workaround, you could transform the latter "else if" clause to a constant "else" clause:
```XML
<Node>
  <!-- if x < 0.5 -->
  <Node>
    <SimplePredicate field="x" operator="lessThan" value="0.5"/>
  </Node>
  <!-- else -->
  <Node>
    <True/>
  </Node>
</Node>
```

This should cut the number of parse operations half (assuming balanced trees) for the current evaluation request.

> That seems kind of excessive since these values never change once the pmml file has been parsed right?

This is excessive, but it cannot be "solved" at the PMML class model level. The return value of `org.dmg.pmml.SimplePredicate#getValue()` will have to be `java.lang.String` (and not eg. `java.lang.Number`), because this predicate type must be able to handle all PMML data types - strings, booleans, date and time types, etc. 

If you know that your tree model will be dealing with numeric values, then it is possible to replace all `org.dmg.pmml.SimplePredicate` object instances with a specialized subclass object instances. The idea is that this subclass contains extra business logic, which parses the `#getValue()` argument once in the beginning of application lifecycle, caches this `java.lang.Number` value, and serves it to all interested parties during the remainder of application lifecycle. It costs some memory (perhaps 25%) though.

There's a class `org.jpmml.evaluator.RichSimplePredicate` available in the `org.jpmml:pmml-evaluator-extension` module:
https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-evaluator-extension/src/main/java/org/jpmml/evaluator/RichSimplePredicate.java

You can "rewrite" your tree model object like this:
```Java
org.dmg.pmml.PMML pmml = ...;

org.jpmml.evaluator.visitors.PredicateOptimizer predicateOptimizer = new org.jpmml.evaluator.visitors.PredicateOptimizer();
predicateOptimizer.applyTo(pmml);
```

The fundamental difference between `SimplePredicate` and `RichSimplePredicate` is that the latter implements value caching, which is made interoperable with the JPMML-Evaluator library using the `org.jpmml.evaluator.HasParsedValue` interface.

If you can think of a better value caching mechanism for your application, then feel free to implement your own `org.dmg.pmml.SimplePredicate & org.jpmml.evaluator.HasParsedValue` subclass.
