### ISSUE TITLE
Maven pulling snapshot dependencies

### ISSUE THREAD

**Issue by DieBauer** [jpmml/jpmml-evaluator#43]
Hi, I'm using this library as a dependency in a maven project. 

```xml
            <dependency>
                <groupId>org.jpmml</groupId>
                <artifactId>pmml-evaluator</artifactId>
                <version>1.3.3</version>
            </dependency>
```
When I compile the project, I get
> [WARNING] The POM for com.google.guava:guava:jar:19.0-SNAPSHOT is missing, no dependency information available
> [WARNING] The POM for org.apache.commons:commons-math3:jar:3.5-SNAPSHOT is missing, no dependency information available

It looks like this is due to the version 'constraint' of guava for example `<version>[14.0, 19.0]</version>`.

The documentation regarding version ranges tell that it is possible to take snapshots into account when resolving them. https://docs.oracle.com/middleware/1221/core/MAVEN/maven_version.htm#MAVEN8903

Why do you use version constraints and not just pick one version? And is there a way to get rid of these SNAPSHOT resolution?

**Comment by vruusmann** [comment]
The JPMML-Evaluator library is typically co-deployed with other Java libraries, which may wish to depend on different versions of Guava, Commons-Math3 etc. libraries.

A version range such as `<version>[14.0, 19.0]</version>` makes it possible for different Java libraries to "negotiate" a Guava version, which will be satisfiable to all of them. Otherwise, every Java library would need to import its own Guava version, which would make application packaging rather difficult.

By default, version ranges only "select" release versions. If your application build is "selecting" snapshot versions as well, then you need to disable the use of snapshot repositories.

> [WARNING] The POM for com.google.guava:guava:jar:19.0-SNAPSHOT is missing, no dependency information available

If you run `mvn clean install` with current JPMML-Evaluator checkout, then there are no such warnings. So, please fix your local environment/build.
