### ISSUE TITLE
[Question]: Handling Missing Values in Child Context

### ISSUE THREAD

**Issue by infiton** [jpmml/jpmml-evaluator#59]
Suppose I have the following PMML snippet:

```xml
<MiningModel functionName="classification">
  <MiningSchema>
    <MiningField name="foo" usageType="active"/>
    <MiningField name="bar" usageType="target"/>
  </MiningSchema>
  <Segmentation multipleModelMethod="average">
     <Segment id="1">
       <True/>
       <TreeModel functionName="classification">
         <MiningSchema>
           <MiningField name="foo" usageType="active" missingValueReplacement="0"/>
           <MiningField name="bar" usageType="target"/>
         </MiningSchema>
         <Node id="1">
         </Node>
       </TreeModel>
     </Segment>
  </Segmentation>
</MiningModel>
```

i.e. the parent model passes the missing value on, but the child model wants to replace it with `0`

from the PMML spec (http://dmg.org/pmml/v4-3/FieldScope.html) we have:

> Since MiningFields have features for manipulating data values that are missing, invalid or considered an outlier, values handled at the top-level (i.e., values that don't pass through the MiningSchema "asIs") will not make it to sub-models.

I don't understand what "will not make it to sub-models" means.

Shouldn't the child model replace the missing value with `0`?

Do you have any insight on this? How does jpmml handle this case?

**Comment by vruusmann** [comment]
> I don't understand what "will not make it to sub-models" means.

The quoted section of the PMML specification is rather obscure. But judging from the context, it should mean that a child model has no way of knowing, if the value that it is seeing is the original user-provided value, or has already been treated by some parent model element.

In you example, if your second-level model (the `/PMML/MiningModel/Segmentation/Segment@id=1/TreeModel` element) had a child model, then this child model would always see missing value-**_treated_** value `foo=0`. The quoted section prohibits it from "jumping up one level", and seeing the missing value-**_untreated_** value `foo=null`, which exist inside your top-level model (the `/PMML/MiningModel` element).

> Shouldn't the child model replace the missing value with 0?

It definitely should.

> How does jpmml handle this case?

The JPMML-Evaluator library should correctly implement the field scoping part of the PMML specification (and, hopefully, all other parts as well). There was a bug in this area in older versions (late 1.1.X development branch), so that a child model could see some "hidden" field values.

Moreover, the above field scoping rules are statically defined, which means that it's possible to analyze the data structure of a model object, and tell exactly which field values/field value treatments are visible/in effect, respectively, in any given location. The JPMML-Model library contains Visitor class `org.jpmml.model.visitors.DeepFieldResolver`, which provides a skeleton implementation for developing field scoping-aware model transformers and optimizers. For example, there's a Visitor class `org.jpmml.model.visitors.MiningSchemaCleaner` which, as its name suggests, is able to compute and enforce the most compact ("minimum viable") representation for all `MiningSchema` elements inside a PMML document.

**Comment by infiton** [comment]
thanks you again for your clear and quick answer! Very much appreciated, I have found the PMML spec on field scopes to be woefully obscure and leaves quite a bit to interpretation.

I agree with your approach, but just wanted to double check.

Thanks again :)
