### ISSUE TITLE
Results returning null

### ISSUE THREAD

**Issue by BellidoGilles** [jpmml/jpmml-evaluator#60]
Hello, 

I skimmed at the issue #52 which seemed to discuss a similar subject but I found it of no help for my situation as it seems that the problem is not (entirely) due to the imported model. I am currently experimenting with jpmml for a project and looking through all the examples and documentation. I tried to import a model using the different given examples. In order to ease the process, I used example models, notably KMeanIris.pmml and DecisionTreeIris.pmml _(4.2 version)_, and three cases from the Iris dataset as my prediction set. _(More precision about the prediction test : I download the Iris dataset as a csv and stripped it from the column Species and all but three raws)_

I imported DecisionTreeIris.pmml and then did the step of preparations and evaluation. All that finished, I can't manage to look at the results to verify the prediction of the model. If I simply try : 
Case 1 : System.out.println(results);
```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Objects.toStringHelper(Ljava/lang/Object;)Lcom/google/common/base/Objects$ToStringHelper;
	at org.jpmml.evaluator.Classification.toStringHelper(Classification.java:96)
	at org.jpmml.evaluator.EntityClassification.toStringHelper(EntityClassification.java:59)
	at org.jpmml.evaluator.tree.NodeScoreDistribution.toStringHelper(NodeScoreDistribution.java:114)
	at org.jpmml.evaluator.Classification.toString(Classification.java:90)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at java.util.AbstractMap.toString(AbstractMap.java:559)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at jpmml.TrainingCode.main(TrainingCode.java:83)
```

Case 2 : System.out.println(results.get(targetFieldName));
```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Objects.toStringHelper(Ljava/lang/Object;)Lcom/google/common/base/Objects$ToStringHelper;
	at org.jpmml.evaluator.Classification.toStringHelper(Classification.java:96)
	at org.jpmml.evaluator.EntityClassification.toStringHelper(EntityClassification.java:59)
	at org.jpmml.evaluator.tree.NodeScoreDistribution.toStringHelper(NodeScoreDistribution.java:114)
	at org.jpmml.evaluator.Classification.toString(Classification.java:90)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at jpmml.azer.main(azer.java:83)
```

Case 3 : System.out.println(results.get(targetFieldName.getValue()));
```
null
```

So here I am wondering how to look at the results, where I went wrong and what I didn't understand about the inner working of jpmml. Also, when I tried the same code with KMeansIris and I observe that there was no TargetFields at all where I expected to see the clusters. Why is that ?

Hoping I don't bother you too much with so trivial questions,
G. BELLIDO

Code 
```
public class TrainingCode {
	public static void main (String[] args) throws Exception{

		/* Loading the pmml file */ 
		PMML pmml;
		try(InputStream is = new FileInputStream(PMML_FILE)){
			pmml = org.jpmml.model.PMMLUtil.unmarshal(is);
		}

		/* Construction of the evaluator */
		ModelEvaluatorFactory modelEvaluatorFactory = ModelEvaluatorFactory.newInstance();
		ModelEvaluator<?> modelEvaluator = modelEvaluatorFactory.newModelEvaluator(pmml);
		Evaluator evaluator = (Evaluator) modelEvaluator;

		/* Loading the data needing prediction */
		BufferedReader br = null;
		String line = "";
		String cvsSplitBy = ",";
		br = new BufferedReader(new FileReader(To_PREDICT.CSV));
		try {
			while ((line = br.readLine()) != null) {
				/* Adding the values of the line in temp */
				Map<String, String> temp =  new LinkedHashMap<String, String>();
				String[] argsLine = line.split(cvsSplitBy);
				temp.put("Sepal_Length", argsLine[0]);
				temp.put("Sepal_Width", argsLine[1]);
				temp.put("Petal_Length", argsLine[2]);
				temp.put("Petal_Width", argsLine[3]);

				/* Transformation of temp into a Map<FieldName, FieldValue> for evaluation */
				Map<FieldName, FieldValue> transformed = prepare(evaluator,temp);

				/* Evaluation */
				Map<FieldName, ?> results = evaluator.evaluate(transformed);

				/* Verifying what are the input Fields */
				List<InputField> inputFields = evaluator.getInputFields();
				for(InputField inputField:inputFields){
					FieldName targetFieldName = inputField.getName();
					System.out.println("	"+targetFieldName);
				}

				/* Verifying what are the output/target Fields */
				List<TargetField> targetFields = evaluator.getTargetFields();
				for(TargetField targetField : targetFields){
					FieldName targetFieldName = targetField.getName();
					System.out.println("	"+targetFieldName);
					/* Verifying if the value associated to the key is null */
					System.out.println("	Valeur : "+(results.get(targetFieldName.getValue())));
				}
			}
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			if (br != null) {
				try {
					br.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		}
	}

	/* Preparing the data as seen in the example */
	public static  Map<FieldName, FieldValue> prepare(Evaluator evaluator, Map<String, ?> arguments){
		Map<FieldName, FieldValue> pmmlarguments = new LinkedHashMap<FieldName, FieldValue>();
		List<InputField> inputFields = evaluator.getActiveFields();

		for(InputField inputField : inputFields){
			FieldName inputFieldName = inputField.getName();
			Object rawValue = arguments.get(inputFieldName.getValue());
			FieldValue fieldValue = inputField.prepare(rawValue);
			pmmlarguments.put(inputFieldName,fieldValue);
		}
		
		return pmmlarguments;
	}
}
```

**Comment by vruusmann** [comment]
The `Evaluator#evaluate(Map)` method returns you a `java.util.Map` instance, which contains field name-value mappings for the target field(s) and output fields. If you "print" it with `System.out.println(results)`, then the map implementation class (should be `java.util.LinkedHashMap` currently) will invoke `Object#toString()` for all field names and values.

For "DecisionTreeIris.pmml" the value of the target field is an instance of `org.jpmml.evaluator.tree.NodeScoreDistribution`, which overrides `Object#toString()`, and uses Google Guava helper class `com.google.common.base.Objects.toStringHelper` for constructing the string result:
https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-evaluator/src/main/java/org/jpmml/evaluator/tree/NodeScoreDistribution.java#L113-L118

However, in you application, this Google Guava helper class cannot be loaded, because it appears to be an incompatible version (signalled by JVM by throwing an instance of `java.lang.NoSuchMethodError`). JPMML-Evaluator is compatible with Google Guava versions in range 14.0 through 20.0. What is your  Google Guava version? Could it be 21.0, which removed (parts of-) the `Objects.toStringHelper()` method?

You can resolve this `java.lang.NoSuchMethodError` by upgrading/downgrading the Google Guava dependency to the correct version.

If you're looking to build a simple application, then perhaps you should get started with the [JPMML-Evaluator-Bootstrap](https://github.com/jpmml/jpmml-evaluator-bootstrap) project. It includes an Apache Maven build file, which shows how to package the JPMML-Evaluator library and its transitive dependencies into an (executable-) uber-JAR file.

> Also, when I tried the same code with KMeansIris and I observe that there was no TargetFields at all where I expected to see the clusters.

"DecisionTreeIris.pmml" contains a classification-type decision tree model, which is a **supervised** learning algorithm. "KMeansIris.pmml" contains a clustering model, which is an **unsupervised** learning algorithm. By definition, unsupervised models do not define a target field, so the `Evaluator#getTargetFields()` method returns an empty `java.util.List` instance (but the `Evaluator#getOutputFields()` method should return a non-empty list).

To some degree, you can distinguish between supervised and unsupervised learning algorithms by querying `Evaluator#getMiningFunction()`. For "DecisionTreeIris.pmml" it would return `MiningFunction.CLASSIFICATION`, and for "KMeansIris.pmml" it would return `MiningFunction.CLUSTERING`.

**Comment by BellidoGilles** [comment]
It was indeed a problem related to Guava version _(21.0)_.  I was so obsessed with the problem the fact that the KMeans was unsupervised totally went over my head. Anyway thank you for those clear answers.
