### ISSUE TITLE
Target Category Size Validation for generalizedLinear classification

### ISSUE THREAD

**Issue by infiton** [jpmml/jpmml-evaluator#61]
consider the following PMML

```xml
<PMML xmlns="http://www.dmg.org/PMML-4_3" version="4.3">
  <Header/>
  <DataDictionary numberOfFields="3">
   <DataField name="x1" optype="continuous" dataType="double"/>
   <DataField name="x2" optype="continuous" dataType="double"/>
   <DataField name="y" optype="categorical" dataType="string">
     <Value value="yes"/>
     <Value value="no"/>
     <Value value="maybe_so"/>
   </DataField>
  </DataDictionary>

  <GeneralRegressionModel modelType="generalizedLinear" modelName="GZLM" functionName="classification" distribution="binomial" linkFunction="logit">
     
    <MiningSchema>
     <MiningField name="x1" usageType="active" missingValueReplacement="0"/>
     <MiningField name="x2" usageType="active"/>
     <MiningField name="y" usageType="target"/>
    </MiningSchema>

    <Output>
     <OutputField name="predicted_y" feature="predictedValue" dataType="string"/>
     <OutputField name="probability_yes" value="yes" feature="probability" optype="continuous" dataType="double"/>
     <OutputField name="probability_no" value="no" feature="probability" optype="continuous" dataType="double"/>
     <OutputField name="probability_maybe_so" value="maybe_so" feature="probability" optype="continuous" dataType="double"/>
    </Output>

    <ParameterList>
      <Parameter name="p0" label="Intercept"/>
      <Parameter name="p1" label="x1"/>
      <Parameter name="p2" label="x2"/>
    </ParameterList>

    <FactorList>
      <Predictor name="x1"/>
      <Predictor name="x2"/>
    </FactorList>

    <PPMatrix>
      <PPCell value="1" predictorName="x1" parameterName="p1"/>
      <PPCell value="1" predictorName="x2" parameterName="p2"/>
    </PPMatrix>

    <ParamMatrix>
      <PCell targetCategory="yes" parameterName="p0" beta="26.836" df="1"/>
      <PCell targetCategory="yes" parameterName="p1" beta="-.719" df="1"/>
      <PCell targetCategory="yes" parameterName="p2" beta="-19.214" df="1"/>
      <PCell targetCategory="no" parameterName="p0" beta="26.836" df="1"/>
      <PCell targetCategory="no" parameterName="p1" beta="-.719" df="1"/>
      <PCell targetCategory="no" parameterName="p2" beta="-19.214" df="1"/>
    </ParamMatrix>

  </GeneralRegressionModel>

</PMML>
```

using `jpmml` to evaluate this with inputs `{x1: 1, x2: 2}` gives, 
```
{
  probability_yes: 0.999999999995455,
  probability_no: 0.999999999995455,
  probability_maybe_so: 4.545031018210466E-12
}
```

I think from http://dmg.org/pmml/v4-3/GeneralRegression.html 

> For a generalized linear model with binomial distribution and a categorical target the predicted probabilities are computed as follows

This makes me think that `modelType="generalizedLinear"` should validate that the number of target categories is exactly 2

Do you think this interpretation is correct?

**Comment by vruusmann** [comment]
Where did you get this PMML document? Or did you simply take some valid model, and started hacking it to see when and how JPMML-Evaluator breaks?

The first "safety/sanity check" should be performed by the PMML producer software. For starters, it should not be permitted to report `GeneralRegressionModel@distribution="binomial"` when the number of categories is not exactly two.

> This makes me think that modelType="generalizedLinear" should validate that the number of target categories is exactly 2.

The problem with extra validation is computational cost. JPMML-Evaluator would be significantly faster if it already wasn't so paranoid.

Anyway, speaking about the above PMML document, how do you know that the data scientist meant to perform binomial classification, and not multinomial one? In other words, what makes you think that JPMML-Evaluator should emit a warning/error "model is not a valid binomial classifier because of structural issues A, B and C", and not "model is not a valid multinomial classifier because of structural issues X, Y and Z"?

**Comment by infiton** [comment]
> Or did you simply take some valid model, and started hacking it to see when and how JPMML-Evaluator breaks?

yah I was just curious about what happens in this case, this is not produced by any producer software

> The problem with extra validation is computational cost. 

fair enough!

I was actually just playing with it to make sure I correctly understood the spec, it sounds like the interpretation is correct, but in this case no one should ever produce a PMML doc such as this
