### ISSUE TITLE
MapXform values are not recognized without quotes

### ISSUE THREAD

**Issue by hannsta** [jpmml/jpmml-evaluator#63]
Using the R MapXform example:

`auditBox <- MapXform(auditBox, xformInfo="[Sex -> d_sex][string->integer]", table="MapGender.csv",mapMissingTo="0")`

Generates the following inline table:
```
     <InlineTable>
      <row>
       <input1>Male</input1>
       <output>1</output>
      </row>
      <row>
       <input1>Female</input1>
       <output>0</output>
      </row>
     </InlineTable>
```

When passing the appropriate values, this will generate an InvalidResultException. To workaround this you can edit the PMML file and surround the input fields in quotes:

```
      <row>
       <input1>"Male"</input1>
       <output>1</output>
      </row>
```

**Comment by vruusmann** [comment]
This error report does not compute - the JPMML-Evaluator does not perform quote addition/removal anywhere (as this kind of behaviour is not part of the PMML specification).

Perhaps you have it backwards - `MapXform` generates quoted values, which must be manually unquoted?

**Comment by vruusmann** [comment]
The content of the `InlineTable` element is parsed using standard Java DOM APIs:
https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-evaluator/src/main/java/org/jpmml/evaluator/InlineTableUtil.java#L80

JPMML-Evaluator uses whatever is provided by `org.w3c.dom.Element#getTextContent()`.

**Comment by hannsta** [comment]
Thanks for your response here. I had the ordering right, which made me think that my input record might have picked up hidden escape characters. However, this would cause problems in many more methods than just MapXForm. (NormDiscreteXForm works just fine with this same data)

```
for(Map<FieldName, ?> inputRecord : inputRecords){
	for(InputField inputField : inputFields){
			FieldName name = inputField.getName();

			arguments.put(name, inputField.prepare(inputRecord.get(name)));
	}
	Map<FieldName, ?> results = evaluator.evaluate(arguments);
```

But, if you are not able to replicate, I am fine chalking this up to user error.

**Comment by vruusmann** [comment]
> But, if you are not able to replicate, I am fine chalking this up to user error.

I haven't figured out the usage of `pmmlTransformations` yet (some obscure syntax, plus external resource files), so I could use little help here.

Can you attach a complete PMML file (eg. based on the "Audit" dataset), plus a couple of input data records in CSV data format?

**Comment by hannsta** [comment]
[audit_clustering.txt](https://github.com/jpmml/jpmml-evaluator/files/1075960/audit_clustering.txt)

[smallaudit.txt](https://github.com/jpmml/jpmml-evaluator/files/1075970/smallaudit.txt)

**Comment by vruusmann** [comment]
Let me guess, you were using the `org.jpmml.evaluator.EvaluationExample` command-line application for testing?

This application splits lines in the CSV file by the cell separator character, and does not perform any additional cell value filtering/normalization. For example, if your CSV file contains a quoted string column, then these quoted cell values will be passed on to the PMML evaluator **_WITH_** leading and trailing quotation marks.

At the moment we have a situation where your `audit.csv` file contains gender cell values `"Male"` and `"Female"`. According to the model schema, they are not valid.

So, instead of quoting values in the `MapValues` transformation, you should unquote gender cell values in your CSV file.

**Comment by hannsta** [comment]
No, this is integrated into another application, where I am passing a string value that (from what I can see) contains no quotations. I have run replaceAll("\"","") on this and ran into the same error.

As I mentioned, this Female value works well when passed through a NormDiscreteXForm transformation that, in this case, does the same thing:

```
   <DerivedField dataType="integer" name="gender_transformed" optype="categorical">
	<NormDiscrete field="Gender" mapMissingTo="0.0" value="Male"/>
   </DerivedField>
```

Are these two interpreted differently?

**Comment by vruusmann** [comment]
I removed quotation marks from your sample CSV file, and tried executing the workflow with `org.jpmml.evaluator.EvaluationExample` command-line application. Indeed, the workflow fails, because the `MapValues` element is invalid.

See lines 30 through 42 in your `audit_clustering.txt` file:
```xml
<MapValues outputColumn="out">
	<FieldColumnPair field="Gender" column="input1"/>
	<InlineTable>
		<row>
			<input1>Male</input1>
			<output>1</output>
		</row>
		<row>
			<input1>Female</input1>
			<output>0</output>
		</row>
	</InlineTable>
</MapValues>
```

It reads "return the value of `out` column as a result", but the nested `InlineTable` element does not contain such column (but there is an `output` column).

**Comment by vruusmann** [comment]
When the `MapValues@outputColumn` attribute is renamed from "out" to "output", then the model scores without problems.

**Comment by hannsta** [comment]
Interesting, that worked for me as well. If you are interested, I have attached the R script that generated this PMML file. 
[map_error_r.txt](https://github.com/jpmml/jpmml-evaluator/files/1076122/map_error_r.txt)

At least there are two easy workarounds!

**Comment by vruusmann** [comment]
When I execute the R script, then the generated `MapValues` element is broken exactly in the same way as detailed in https://github.com/jpmml/jpmml-evaluator/issues/63#issuecomment-308577126.
