### ISSUE TITLE
Do AssocationModels support inputFields that are of continuous data type

### ISSUE THREAD

**Issue by mariobriggs** [jpmml/jpmml-evaluator#80]
I have an association model. When i run an evaluate, i run into an exception at https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-evaluator/src/main/java/org/jpmml/evaluator/association/AssociationModelEvaluator.java#L291

The code seems to indicate that only CATEGORICAL types are supported here
 
https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-evaluator/src/main/java/org/jpmml/evaluator/association/AssociationModelEvaluator.java#L271

Would be helpful if someone can comment. The spec http://dmg.org/pmml/v4-1/DataDictionary.html seems to indicate continuous types are possible

**Comment by vruusmann** [comment]
> I have an association model.

What software did you use to produce it? By any chance, can you share your file, or build a shareable example file using some toy dataset?

> The code seems to indicate that only CATEGORICAL types are supported here

The check for the operational type of a field (continuous, categorical or ordinal) should be seen as a sanity check - it does not make sense to use continuous values in this context, because the goal is to match items using the equality operator `==`.

**Comment by mariobriggs** [comment]
@vruusmann checking if can share.

**Comment by mariobriggs** [comment]
@vruusmann shared via direct email for starters (your github profile listed email)

**Comment by vruusmann** [comment]
@mariobriggs Got the example file - thanks!

In brief, the current implementation of `AssociationModelEvaluator` is naive-ish, because it expects all item values to be defined by input fields directly. However, in your case, item values are defined by derived fields (eg. a binning function applied to a continuous input field, which results in a categorical derived field).

To solve the problem, `AssociationModelEvaluator` should be iterating over the `Item` child elements of the `AssociationModel` element in these two locations:
https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-evaluator/src/main/java/org/jpmml/evaluator/association/AssociationModelEvaluator.java#L261
https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-evaluator/src/main/java/org/jpmml/evaluator/association/AssociationModelEvaluator.java#L307

For example:
```Java
List<Item> items = associationModel.getItems();
for(Item item : items){
	FieldName name = item.getField(); // THIS!
	FieldValue value = context.evaluate(name);

	// Proceed as usual
}
```

**Comment by mariobriggs** [comment]
So i replaced
 ```
for(InputField activeField : activeFields){
	FieldName name = activeField.getName();
	FieldValue value = context.evaluate(name);
``` 
with
 ```List<Item> items = associationModel.getItems();
for(Item item : items){
	FieldName name = item.getField(); // THIS!
	FieldValue value = context.evaluate(name);
```

it didnt help since each item only has the value field populated as 'name-value' and hence runs into NPE's with many tests built in

**Comment by mariobriggs** [comment]
@vruusmann thank you. Verified that work in 1.3.11

**Comment by vruusmann** [comment]
I would argue that your PMML document (that you sent to me for demonstration purposes) is/was not valid according to the PMML specification - `Item` elements are not allowed to reference `DerivedField` elements. See: http://mantis.dmg.org/view.php?id=195

In that sense, JPMML-Evaluator is violating the PMML specification now (but is doing so for greater good).
