### ISSUE TITLE
JPMML PMML file (version=4.1)  gives error

### ISSUE THREAD

**Issue by SandyWare** [jpmml/jpmml-evaluator#92]
When I tried JPMML with attached PMML file (version=4.1) and RegressionModel, it gives me error.  
I tried with below
 **command :** 
```
java -cp pmml-evaluator-example/target/example-1.3-SNAPSHOT.jar org.jpmml.evaluator.TestingExample --model DefaultValueTest.pmml --input input.csv  --expected-output expected-output.csv
```

**Error :** 
```
Exception in thread "main" java.lang.IllegalArgumentException
	at org.jpmml.evaluator.CsvUtil.getSeparator(CsvUtil.java:108)
	at org.jpmml.evaluator.CsvUtil.readTable(CsvUtil.java:60)
	at org.jpmml.evaluator.Example.readTable(Example.java:109)
	at org.jpmml.evaluator.TestingExample.execute(TestingExample.java:121)
	at org.jpmml.evaluator.Example.execute(Example.java:86)
	at org.jpmml.evaluator.TestingExample.main(TestingExample.java:112)
```

Please refer attachment for more detail.

[jpmml-evaluator.zip](https://github.com/jpmml/jpmml-evaluator/files/1570837/jpmml-evaluator.zip)

**Comment by vruusmann** [comment]
The `org.jpmml.evaluator.TestingExample` command-line application throws this exception, because it can't understand the format of your input CSV file - it doesn't make sense to have a single-column CSV file, where there's a comma character at the end of each line (is the comma part of field value or not?).

Please fix your input CSV file, or better yet, use a more realistic sample.

For getting started, I would suggest using the following files (can be found inside `pmml-rattle` or `pmml-knime` integration testing modules): `--input Iris.csv --model DecisionTreeIris.pmml --expected-output DecisionTreeIris.csv`.

**Comment by SandyWare** [comment]
Thanks lot for quick solution.
My requirement is  to  Process RegressionModel / GeneralRegressionModel on customer PMML and input csv file. But I don't have any output PMML file to compare the result. 
So how I can do it using JPMML for RegressionModel / GeneralRegressionModel model ?

So I am expecting syntax look like below  : 
Example: 
 // here I don't have have expected output file to provide.
 java -cp pmml-evaluator-example/target/example-1.3-SNAPSHOT.jar --input input.csv > output_result.csv

Your suggestion and help is highly appreciated.

**Comment by SandyWare** [comment]
find solution, command as below  :
java -cp pmml-evaluator-example/target/example-1.3-SNAPSHOT.jar org.jpmml.evaluator.EvaluationExample --model DefaultValueTest.pmml --input input.csv --output SW_output.csv --separator ";
